repos:
  - repo: https://github.com/ambv/black
    rev: 25.1.0
    hooks:
      - id: black
        name: black
        language: python
        types: [python]
        description: "Black: The uncompromising Python code formatter"
        # language_version: python3.9
        files: \.(py)$
  - repo: https://github.com/PyCQA/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        files: \.(py)$
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.0
    hooks:
      # Run the linter.
      - id: ruff-check
        files: \.(py)$
      # Run the formatter.
      - id: ruff-format
        files: \.(py)$
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.3  # Replace with latest tag
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [pre-commit]
  - repo: https://github.com/rtts/djhtml
    rev: 'main'  # replace with the latest tag on GitHub
    hooks:
      - id: djhtml
      - id: djcss
      - id: djjs