# Generated by Django 4.0.2 on 2022-02-21 14:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plannerapp', '0002_absences_delete_employees'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='absences',
            new_name='absence',
        ),
    ]
