# Generated by Django 4.0.2 on 2022-02-23 10:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plannerapp', '0003_rename_absences_absence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='absence_date',
            field=models.DateField(max_length=200),
        ),
        migrations.AlterField(
            model_name='absence',
            name='request_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
