# Generated by Django 4.0.2 on 2022-02-23 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plannerapp', '0004_alter_absence_absence_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absence',
            old_name='absence_date',
            new_name='absence_date_end',
        ),
        migrations.AddField(
            model_name='absence',
            name='absence_date_start',
            field=models.DateField(default=django.utils.timezone.now, max_length=200),
        ),
        migrations.AlterField(
            model_name='absence',
            name='User_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to=settings.AUTH_USER_MODEL),
        ),
    ]
