# Generated by Django 3.2.9 on 2022-05-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannerapp', '0005_rename_absence_date_absence_absence_date_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='absence_date_start',
            field=models.DateField(max_length=200),
        ),
    ]
