# Generated by Django 3.2.9 on 2022-05-19 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plannerapp', '0006_alter_absence_absence_date_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='reason',
        ),
    ]
