# Generated by Django 3.2.9 on 2022-05-17 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plannerapp', '0007_relationship_status_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='Role',
        ),
        migrations.RenameField(
            model_name='relationship',
            old_name='status',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='relationship',
            old_name='Team',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='status',
            new_name='role',
        ),
    ]
