# Generated by Django 3.2.9 on 2022-05-17 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plannerapp', '0010_alter_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='creator',
        ),
    ]
