# Generated by Django 3.2.9 on 2022-05-19 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plannerapp', '0007_remove_absence_reason'),
        ('plannerapp', '0011_remove_team_creator'),
    ]

    operations = [
    ]
