# Generated by Django 3.2.9 on 2022-05-19 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plannerapp', '0011_merge_0007_remove_absence_reason_0010_alter_team_name'),
        ('plannerapp', '0012_merge_20220519_1234'),
    ]

    operations = [
    ]
