# Generated by Django 3.2.9 on 2022-05-20 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plannerapp', '0013_merge_20220519_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='manager_ID',
        ),
        migrations.RemoveField(
            model_name='absence',
            name='request_accepted',
        ),
        migrations.RemoveField(
            model_name='absence',
            name='request_date',
        ),
    ]
