# Generated by Django 3.2.9 on 2022-05-27 09:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plannerapp', '0014_auto_20220520_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='edit_whitelist',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
