# Generated by Django 3.2.9 on 2022-05-27 12:09

from django.db import migrations
import django.db.models.deletion
import river.models.fields.state


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0002_auto_20220527_1308'),
        ('plannerapp', '0014_auto_20220520_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='status',
            field=river.models.fields.state.StateField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='river.state'),
        ),
    ]
