# Generated by Django 3.2.9 on 2022-07-01 08:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ap_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='absence_date_start',
            field=models.DateField(default=django.utils.timezone.now, max_length=200, verbose_name='Date'),
        ),
    ]
