# Generated by Django 3.2.9 on 2022-06-28 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ap_app', '0002_userextend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserExtend',
        ),
    ]
