# Generated by Django 4.2.6 on 2024-05-22 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ap_app", "0003_recurringexception"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColourScheme",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("default", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ColorData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("color", models.CharField(max_length=20)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colorscheme",
                        to="ap_app.colourscheme",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
