# Generated by Django 3.2.9 on 2022-10-24 12:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ap_app', '0003_alter_team_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='notes',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
