# Generated by Django 3.2.9 on 2022-07-01 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ap_app', '0002_alter_absence_absence_date_start'),
        ('ap_app', '0004_userprofile'),
    ]

    operations = [
    ]
