# Generated by Django 4.2.6 on 2024-05-23 09:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ap_app", "0004_colourscheme_colordata"),
    ]

    operations = [
        migrations.RenameField(
            model_name="colordata",
            old_name="name",
            new_name="scheme",
        ),
    ]
