# Generated by Django 3.2.9 on 2023-06-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap_app', '0005_recurringabsences_target_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='region',
            field=models.CharField(default='GB', max_length=200),
        ),
    ]
