# Generated by Django 3.2.9 on 2022-07-05 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ap_app', '0005_merge_20220701_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='edit_whitelist',
        ),
    ]
