# Generated by Django 3.2.9 on 2023-02-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap_app', '0005_recurringabsences_target_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='half_day',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('EVENING', 'Evening'), ('MORNING', 'Morning')], default='NORMAL', max_length=9),
        ),
    ]
