# Generated by Django 4.2.6 on 2024-06-10 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ap_app', '0005_rename_name_colordata_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colourscheme',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='colordata',
            unique_together={('user', 'scheme')},
        ),
    ]
