# Generated by Django 3.2.9 on 2023-06-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap_app', '0006_absence_half_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='half_day',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('AFTERNOON', 'Afternoon'), ('MORNING', 'Morning')], default='NORMAL', max_length=200),
        ),
    ]
