# Generated by Django 3.2.9 on 2022-07-05 10:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ap_app', '0006_remove_absence_edit_whitelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='edit_whitelist',
            field=models.ManyToManyField(related_name='_ap_app_userprofile_edit_whitelist_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
