# Generated by Django 4.2.6 on 2024-06-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap_app', '0006_alter_colourscheme_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='external_teams',
            field=models.BooleanField(default=True),
        ),
    ]
