# Generated by Django 4.2.6 on 2024-10-28 08:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ap_app", "0007_alter_userprofile_external_teams"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Relationship",
        ),
        migrations.DeleteModel(
            name="Team",
        ),
    ]
