# Generated by Django 3.2.9 on 2023-06-16 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ap_app', '0006_userprofile_region'),
        ('ap_app', '0007_alter_absence_half_day'),
    ]

    operations = [
    ]
