# Generated by Django 3.2.9 on 2022-07-06 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ap_app', '0008_absence_target_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='Target_User_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
