# Generated by Django 4.2.6 on 2025-05-21 10:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ap_app", "0008_delete_relationship_delete_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="external_teams",
        ),
    ]
