# Generated by Django 3.2.9 on 2023-06-27 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ap_app', '0008_merge_20230616_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='half_day',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='region',
        ),
    ]
