# Generated by Django 3.2.9 on 2023-06-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap_app', '0009_auto_20230627_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='half_day',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('AFTERNOON', 'Afternoon'), ('MORNING', 'Morning')], default='NORMAL', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='region',
            field=models.CharField(default='GB', max_length=200),
        ),
    ]
