# Generated by Django 3.2.9 on 2023-07-05 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ap_app', '0010_auto_20230627_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='Target_User_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='absence',
            name='User_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
