# Generated by Django 3.2.9 on 2022-07-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap_app', '0010_alter_userprofile_edit_whitelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='privacy',
            field=models.BooleanField(default=False),
        ),
    ]
